server:
  port: 8084

spring:
  application:
    name: authBeta-module

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    status-page-url: http://localhost:8100/status
#    health-check-url-path: http://localhost:8100/health