server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/LoadBalancingDB?useSSL=false&&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul


  #  security:
#    user:
#      name: user
#      password: 1234
  application:
    name: auth-module
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    status-page-url: http://localhost:8100/status
#    health-check-url-path: http://localhost:8100/health